language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - elasticsearch

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.2.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.3.2.deb
  - sudo service elasticsearch restart

before_script:
  - sleep 10
  - composer install -o
