language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - elasticsearch

before_install:
  - sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.3.0
  - sudo service elasticsearch restart

before_script:
  - sleep 10
  - composer install -o
