language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - elasticsearch

addons:
  apt:
    sources:
      - elasticsearch-2.3
    packages:
      - elasticsearch

before_install:
  - sudo service elasticsearch restart

before_script:
  - sleep 10
  - "curl http://localhost:9200/"
  - composer install -o
