sudo: true
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-2.3.2.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.3.2.deb
  - sudo service elasticsearch start

before_script:
  - sleep 20
  - "curl http://localhost:9200/"
  - composer install -o
