language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    sources:
      - elasticsearch-2.3.2
    packages:
      - elasticsearch

services:
  - elasticsearch

before_install:
  - sleep 10
