language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.tar.gz
  - tar zxvf elasticsearch-5.1.1.tar.gz
  - ./elasticsearch-5.1.1/bin/elasticsearch &

before_script:
  - sleep 20
  - "curl http://localhost:9200/"
  - composer install -o
